from constants import *

# DEBUG SETTINGS
SHOW_CHUNK_BORDERS = True

# WINDOW SETTINGS
SCREEN_WIDTH = 500
SCREEN_HEIGHT = 500
FPS = 60

# GRID SETTINGS
TILE_SIZE = 50
CHUNK_SIZE = 6

# PLAYER SETTINGS
PLAYER_SPEED = 5

# OBJECT COLORS
BACKGROUND_COLOR = BLUE
CHUNK_BORDER_COLOR = RED